[storage]
driver = "overlay"
graphRoot = "/home/poduser/.local/share/containers/storage"
runRoot = "/run/user/1000"

[storage.options.overlay]
mount_program = "/usr/bin/fuse-overlayfs"
skip_mount_home = "true"
